version: '3'

networks:
  default:
    external:
      name: traefik

services:
  app:
    depends_on:
      - traefik
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(\"${APP_URI}\")"  # Change to your domain
      - "traefik.http.routers.app.tls.certresolver=myresolver"  # Use the Let's Encrypt resolver
      - "traefik.http.services.app.loadbalancer.server.port=80"
    volumes:
      - .:/var/www/laravel
    
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"  # Use TLS challenge for Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.email=alex-khrist98@mail.ru"  # Change to your email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"  # Storage for certificates
    ports:
      - "80:80"                 # Expose port 80 for HTTP
      - "443:443"
      - "8080:8080"               # Expose port 443 for HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allow Traefik to access Docker socket
      - "./letsencrypt:/letsencrypt"
